version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
  redis:
    image: redis
    volumes:
      - /data/db/redis
    ports:
      - "6379:6379"